<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Exercise;
use App\Models\ExerciseImage;

class ExerciseSeeder extends Seeder
{
    public function run()
    {
        $exercises = [
            // PIERNAS (10 ejercicios)
            [
                'name' => 'Peso muerto',
                'description' => "Ejercicio fundamental para fortalecer glúteos, isquiotibiales y zona lumbar con técnica adecuada.\nInstrucciones y recomendaciones:\n- Mantén los pies separados al ancho de los hombros.\n- Flexiona las caderas hacia atrás manteniendo la espalda recta.\n- Desciende hasta sentir estiramiento en los isquiotibiales.\n- Empuja las caderas hacia adelante para regresar a la posición inicial.\n- Haz 3 series de 8-10 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 20,
                'calories_burned' => 150,
                'equipment' => 'Mancuernas o barra',
                'muscle_group' => 'Piernas',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Zancadas',
                'description' => "Ejercicio unilateral que fortalece piernas y glúteos mientras mejora el equilibrio y estabilidad.\nInstrucciones y recomendaciones:\n- Da un paso largo hacia adelante manteniendo el torso erguido.\n- Flexiona ambas rodillas hasta formar ángulos de 90 grados.\n- Empuja con el talón delantero para regresar a la posición inicial.\n- Alterna las piernas o completa una serie por lado.\n- Haz 3 series de 10-12 repeticiones por pierna.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 15,
                'calories_burned' => 120,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Elevaciones de talones',
                'description' => "Fortalece los músculos de la pantorrilla y mejora la potencia en la parte inferior de las piernas.\nInstrucciones y recomendaciones:\n- Mantente de pie con los pies separados al ancho de los hombros.\n- Eleva los talones lo más alto posible contrayendo las pantorrillas.\n- Mantén la posición por un segundo en la parte superior.\n- Desciende lentamente hasta la posición inicial.\n- Haz 3 series de 15-20 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 80,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Paso lateral',
                'description' => "Ejercicio lateral que activa glúteos medios y fortalece las piernas en el plano frontal.\nInstrucciones y recomendaciones:\n- Mantente de pie con los pies juntos.\n- Da un paso amplio hacia un lado flexionando esa rodilla.\n- Mantén la pierna opuesta extendida.\n- Empuja con el talón para regresar al centro.\n- Haz 2-3 series de 12-15 repeticiones por lado.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 90,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Puente de glúteo',
                'description' => "Activa y fortalece los glúteos mientras mejora la estabilidad del core y cadera.\nInstrucciones y recomendaciones:\n- Acuéstate boca arriba con las rodillas flexionadas.\n- Apoya los pies en el suelo separados al ancho de las caderas.\n- Eleva las caderas contrayendo los glúteos.\n- Mantén la posición por 2 segundos.\n- Haz 3 series de 12-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 85,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Saltos en tijera',
                'description' => "Ejercicio cardiovascular que fortalece piernas y mejora la coordinación y resistencia.\nInstrucciones y recomendaciones:\n- Comienza de pie con los pies juntos y brazos a los costados.\n- Salta separando las piernas y elevando los brazos sobre la cabeza.\n- Salta nuevamente para regresar a la posición inicial.\n- Mantén un ritmo constante y controlado.\n- Haz 3 series de 30-45 segundos.",
                'category' => 'Cardio',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 100,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Estocadas inversas',
                'description' => "Variante de zancada que enfatiza el trabajo de glúteos y reduce el estrés en las rodillas.\nInstrucciones y recomendaciones:\n- Mantente de pie con los pies separados al ancho de las caderas.\n- Da un paso largo hacia atrás con una pierna.\n- Flexiona ambas rodillas hasta formar ángulos de 90 grados.\n- Empuja con el talón delantero para regresar al centro.\n- Haz 3 series de 10-12 repeticiones por pierna.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 130,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Sentadilla búlgara',
                'description' => "Ejercicio unilateral avanzado que desarrolla fuerza y estabilidad en piernas.\nInstrucciones y recomendaciones:\n- Colócate de espaldas a un banco con un pie apoyado sobre él.\n- Desciende flexionando la rodilla delantera hasta 90 grados.\n- Mantén el torso erguido y el peso en el talón delantero.\n- Empuja para regresar a la posición inicial.\n- Haz 3 series de 8-10 repeticiones por pierna.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 18,
                'calories_burned' => 140,
                'equipment' => 'Banco o silla',
                'muscle_group' => 'Piernas',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Salto en caja',
                'description' => "Ejercicio pliométrico que desarrolla potencia explosiva en las piernas.\nInstrucciones y recomendaciones:\n- Colócate frente a una caja o escalón estable.\n- Flexiona ligeramente las rodillas y salta hacia arriba.\n- Aterriza suavemente en la caja con ambos pies.\n- Baja caminando o saltando hacia atrás.\n- Haz 3 series de 5-8 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 15,
                'calories_burned' => 160,
                'equipment' => 'Caja o escalón',
                'muscle_group' => 'Piernas',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Caminar en cuclillas',
                'description' => "Ejercicio isométrico que mantiene tensión constante en cuádriceps y glúteos.\nInstrucciones y recomendaciones:\n- Adopta una posición de sentadilla con muslos paralelos al suelo.\n- Camina hacia adelante manteniendo la posición baja.\n- Da pasos cortos sin elevarte.\n- Mantén el torso erguido y el peso en los talones.\n- Haz 2-3 series de 20-30 pasos.",
                'category' => 'Resistencia',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 110,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Piernas',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],

            // BRAZOS (10 ejercicios)
            [
                'name' => 'Curl de bíceps',
                'description' => "Ejercicio aislado fundamental para desarrollar la masa muscular de los bíceps.\nInstrucciones y recomendaciones:\n- Mantente de pie con una mancuerna en cada mano.\n- Mantén los codos pegados al torso.\n- Flexiona los codos elevando las mancuernas hacia los hombros.\n- Desciende lentamente controlando el peso.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 90,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Brazos',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Extensión de tríceps',
                'description' => "Ejercicio específico para fortalecer y definir la parte posterior del brazo.\nInstrucciones y recomendaciones:\n- Mantente de pie con una mancuerna en ambas manos sobre la cabeza.\n- Flexiona los codos bajando el peso detrás de la cabeza.\n- Mantén los codos fijos y apuntando hacia adelante.\n- Extiende los brazos para regresar a la posición inicial.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 85,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Brazos',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones diamante',
                'description' => "Variante de flexión que enfatiza el trabajo de tríceps y zona interna del pecho.\nInstrucciones y recomendaciones:\n- Adopta posición de flexión con las manos formando un diamante.\n- Mantén el cuerpo recto desde la cabeza hasta los talones.\n- Desciende hasta que el pecho toque las manos.\n- Empuja para regresar a la posición inicial.\n- Haz 3 series de 6-10 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 10,
                'calories_burned' => 120,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Brazos',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Fondos en silla',
                'description' => "Ejercicio para tríceps usando el peso corporal con apoyo en una silla o banco.\nInstrucciones y recomendaciones:\n- Siéntate en el borde de una silla con las manos apoyadas a los lados.\n- Desliza el cuerpo hacia adelante manteniendo las manos en la silla.\n- Desciende flexionando los codos hasta 90 grados.\n- Empuja para regresar a la posición inicial.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 100,
                'equipment' => 'Silla o banco',
                'muscle_group' => 'Brazos',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Curl martillo',
                'description' => "Variante del curl que trabaja bíceps y braquiorradial con agarre neutro.\nInstrucciones y recomendaciones:\n- Mantente de pie con mancuernas en posición neutral (palmas hacia adentro).\n- Mantén los codos pegados al torso.\n- Flexiona los codos elevando las mancuernas como si fueras a martillar.\n- Desciende lentamente controlando el movimiento.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 90,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Brazos',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Press francés',
                'description' => "Ejercicio acostado que aísla eficazmente los tríceps con movimiento controlado.\nInstrucciones y recomendaciones:\n- Acuéstate en un banco con mancuernas extendidas sobre el pecho.\n- Flexiona solo los codos bajando el peso hacia la frente.\n- Mantén los brazos superiores fijos y perpendiculares al suelo.\n- Extiende los codos para regresar a la posición inicial.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 95,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Brazos',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones archer',
                'description' => "Flexión unilateral avanzada que desarrolla fuerza asimétrica en brazos.\nInstrucciones y recomendaciones:\n- Adopta posición de flexión con brazos muy separados.\n- Desciende hacia un lado concentrando el peso en un brazo.\n- El brazo opuesto se mantiene extendido para apoyo.\n- Empuja para regresar al centro y repite al otro lado.\n- Haz 3 series de 4-6 repeticiones por lado.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 15,
                'calories_burned' => 140,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Brazos',
                'intensity' => 'Muy alta',
                'is_active' => true,
            ],
            [
                'name' => 'Curl concentrado',
                'description' => "Ejercicio de aislamiento que permite máxima concentración en el bíceps.\nInstrucciones y recomendaciones:\n- Siéntate con las piernas separadas y apoya el codo en el muslo.\n- Sostén una mancuerna con el brazo completamente extendido.\n- Flexiona el codo elevando el peso hacia el hombro.\n- Desciende lentamente sintiendo el estiramiento.\n- Haz 3 series de 10-12 repeticiones por brazo.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 80,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Brazos',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Patadas de tríceps',
                'description' => "Ejercicio de aislamiento que define y fortalece la parte posterior del brazo.\nInstrucciones y recomendaciones:\n- Inclínate hacia adelante con una rodilla y mano apoyadas en banco.\n- Mantén el brazo superior paralelo al suelo.\n- Extiende el codo llevando la mancuerna hacia atrás.\n- Contrae el tríceps en la posición final.\n- Haz 3 series de 12-15 repeticiones por brazo.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 85,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Brazos',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones en pica',
                'description' => "Preparación para flexiones verticales que enfatiza hombros y tríceps.\nInstrucciones y recomendaciones:\n- Adopta posición de flexión elevando las caderas en forma de V invertida.\n- Mantén las piernas lo más rectas posible.\n- Desciende la cabeza hacia el suelo flexionando los codos.\n- Empuja para regresar a la posición inicial.\n- Haz 3 series de 6-10 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 110,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Brazos',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],

            // PECHO (10 ejercicios)
            [
                'name' => 'Press de pecho con mancuernas',
                'description' => "Ejercicio fundamental para desarrollar masa y fuerza en el pecho con mayor rango de movimiento.\nInstrucciones y recomendaciones:\n- Acuéstate en un banco con mancuernas a la altura del pecho.\n- Empuja las mancuernas hacia arriba hasta extender los brazos.\n- Desciende controladamente hasta sentir estiramiento en el pecho.\n- Mantén los omóplatos retraídos durante todo el movimiento.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 20,
                'calories_burned' => 140,
                'equipment' => 'Mancuernas y banco',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Aperturas con mancuernas',
                'description' => "Ejercicio de aislamiento que estira y contrae el pecho con movimiento de arco.\nInstrucciones y recomendaciones:\n- Acuéstate en banco con mancuernas extendidas sobre el pecho.\n- Abre los brazos en arco manteniendo una ligera flexión en los codos.\n- Desciende hasta sentir estiramiento en el pecho.\n- Regresa por el mismo arco contrayendo el pecho.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 120,
                'equipment' => 'Mancuernas y banco',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones declinadas',
                'description' => "Variante elevada que enfatiza la parte superior del pecho y hombros.\nInstrucciones y recomendaciones:\n- Coloca los pies en un banco y las manos en el suelo.\n- Mantén el cuerpo recto desde los talones hasta la cabeza.\n- Desciende hasta que el pecho casi toque el suelo.\n- Empuja para regresar a la posición inicial.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 130,
                'equipment' => 'Banco o escalón',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones inclinadas',
                'description' => "Variante con manos elevadas que facilita el movimiento y enfatiza pecho inferior.\nInstrucciones y recomendaciones:\n- Coloca las manos en un banco y los pies en el suelo.\n- Mantén el cuerpo recto en línea diagonal.\n- Desciende hasta que el pecho toque el banco.\n- Empuja para regresar a la posición inicial.\n- Haz 3 series de 10-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 100,
                'equipment' => 'Banco o escalón',
                'muscle_group' => 'Pecho',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Press de pecho inclinado',
                'description' => "Variante que trabaja específicamente la parte superior del pecho.\nInstrucciones y recomendaciones:\n- Acuéstate en banco inclinado a 30-45 grados.\n- Empuja las mancuernas desde la altura del pecho hacia arriba.\n- Mantén los omóplatos retraídos y el core activado.\n- Desciende controladamente hasta el estiramiento.\n- Haz 3 series de 8-10 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 18,
                'calories_burned' => 135,
                'equipment' => 'Mancuernas y banco inclinado',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones con palmada',
                'description' => "Ejercicio pliométrico que desarrolla potencia explosiva en el tren superior.\nInstrucciones y recomendaciones:\n- Adopta posición de flexión estándar.\n- Desciende hasta el suelo y empuja explosivamente.\n- Da una palmada en el aire antes de aterrizar.\n- Aterriza suavemente y repite el movimiento.\n- Haz 3 series de 5-8 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 10,
                'calories_burned' => 150,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Pecho',
                'intensity' => 'Muy alta',
                'is_active' => true,
            ],
            [
                'name' => 'Pullover con mancuerna',
                'description' => "Ejercicio que estira y fortalece pecho mientras trabaja serratos y dorsales.\nInstrucciones y recomendaciones:\n- Acuéstate perpendicular a un banco con solo los omóplatos apoyados.\n- Sostén una mancuerna con ambas manos sobre el pecho.\n- Baja la mancuerna detrás de la cabeza en arco.\n- Regresa a la posición inicial sintiendo el estiramiento.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 110,
                'equipment' => 'Mancuerna y banco',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones anchas',
                'description' => "Variante con manos separadas que enfatiza el trabajo del pecho exterior.\nInstrucciones y recomendaciones:\n- Adopta posición de flexión con manos más separadas que los hombros.\n- Mantén el cuerpo recto desde la cabeza hasta los talones.\n- Desciende hasta que el pecho casi toque el suelo.\n- Empuja enfocándote en contraer el pecho.\n- Haz 3 series de 10-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 115,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Press de pecho declinado',
                'description' => "Variante que enfatiza la parte inferior del pecho con ángulo descendente.\nInstrucciones y recomendaciones:\n- Acuéstate en banco declinado con los pies asegurados.\n- Empuja las mancuernas desde la parte inferior del pecho.\n- Mantén control total del movimiento.\n- Desciende hasta sentir estiramiento en la parte baja del pecho.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 18,
                'calories_burned' => 125,
                'equipment' => 'Mancuernas y banco declinado',
                'muscle_group' => 'Pecho',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones hindú',
                'description' => "Movimiento fluido que combina flexión con estiramiento, trabajando todo el cuerpo.\nInstrucciones y recomendaciones:\n- Comienza en posición de flexión con caderas elevadas.\n- Desciende en arco llevando el pecho hacia adelante y abajo.\n- Termina con pecho arriba y brazos extendidos como cobra.\n- Regresa por el mismo camino a la posición inicial.\n- Haz 2-3 series de 6-10 repeticiones.",
                'category' => 'Flexibilidad',
                'difficulty' => 'avanzado',
                'duration' => 15,
                'calories_burned' => 140,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Pecho',
                'intensity' => 'Alta',
                'is_active' => true,
            ],

            // ESPALDA (10 ejercicios)
            [
                'name' => 'Remo con mancuernas',
                'description' => "Ejercicio fundamental para fortalecer toda la musculatura de la espalda.\nInstrucciones y recomendaciones:\n- Inclínate hacia adelante con las rodillas ligeramente flexionadas.\n- Sostén mancuernas con los brazos extendidos hacia el suelo.\n- Tira de los codos hacia atrás contrayendo los omóplatos.\n- Desciende controladamente sintiendo el estiramiento.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 18,
                'calories_burned' => 130,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Espalda',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Dominadas asistidas',
                'description' => "Versión modificada del ejercicio rey para la espalda, adaptado a diferentes niveles.\nInstrucciones y recomendaciones:\n- Cuelga de una barra con agarre pronado más ancho que los hombros.\n- Usa banda elástica bajo los pies para asistencia.\n- Tira del cuerpo hacia arriba hasta que la barbilla pase la barra.\n- Desciende controladamente hasta extensión completa.\n- Haz 3 series de 5-8 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 120,
                'equipment' => 'Barra y banda elástica',
                'muscle_group' => 'Espalda',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Superman',
                'description' => "Ejercicio isométrico que fortalece la zona lumbar y mejora la postura.\nInstrucciones y recomendaciones:\n- Acuéstate boca abajo con brazos extendidos hacia adelante.\n- Eleva simultáneamente el pecho, brazos y piernas del suelo.\n- Mantén la posición contrayendo la espalda baja.\n- Desciende lentamente y repite.\n- Haz 3 series de 12-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 80,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Espalda',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Remo invertido',
                'description' => "Ejercicio horizontal que usa el peso corporal para fortalecer la espalda.\nInstrucciones y recomendaciones:\n- Acuéstate bajo una barra o mesa resistente.\n- Agarra la barra con las manos separadas al ancho de los hombros.\n- Tira del pecho hacia la barra manteniendo el cuerpo recto.\n- Desciende controladamente hasta extensión completa.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 110,
                'equipment' => 'Barra baja o mesa',
                'muscle_group' => 'Espalda',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Jalón con banda elástica',
                'description' => "Simula el movimiento de jalón dorsal usando resistencia variable.\nInstrucciones y recomendaciones:\n- Ancla la banda elástica en un punto alto.\n- Agarra los extremos con los brazos extendidos hacia arriba.\n- Tira hacia abajo y atrás llevando los codos al torso.\n- Contrae los omóplatos en la posición final.\n- Haz 3 series de 12-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 90,
                'equipment' => 'Banda elástica',
                'muscle_group' => 'Espalda',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Buenos días',
                'description' => "Ejercicio de bisagra de cadera que fortalece erectores espinales y glúteos.\nInstrucciones y recomendaciones:\n- Mantente de pie con las manos detrás de la cabeza.\n- Flexiona las caderas hacia atrás manteniendo la espalda recta.\n- Desciende hasta sentir estiramiento en los isquiotibiales.\n- Regresa empujando las caderas hacia adelante.\n- Haz 3 series de 10-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 100,
                'equipment' => 'Peso corporal o mancuernas',
                'muscle_group' => 'Espalda',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Remo unilateral',
                'description' => "Variante que permite trabajar cada lado de la espalda independientemente.\nInstrucciones y recomendaciones:\n- Apoya una rodilla y mano en un banco.\n- Sostén una mancuerna con el brazo libre extendido.\n- Tira del codo hacia atrás contrayendo el omóplato.\n- Desciende controladamente sintiendo el estiramiento.\n- Haz 3 series de 10-12 repeticiones por lado.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 16,
                'calories_burned' => 115,
                'equipment' => 'Mancuerna y banco',
                'muscle_group' => 'Espalda',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Face pull con banda',
                'description' => "Ejercicio correctivo que fortalece romboides y mejora la postura de hombros.\nInstrucciones y recomendaciones:\n- Ancla la banda a la altura de los ojos.\n- Agarra los extremos y tira hacia la cara.\n- Separa las manos y lleva los codos hacia atrás.\n- Contrae los músculos entre los omóplatos.\n- Haz 3 series de 15-20 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 75,
                'equipment' => 'Banda elástica',
                'muscle_group' => 'Espalda',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Hiperextensiones',
                'description' => "Fortalece específicamente la zona lumbar y mejora la estabilidad del core.\nInstrucciones y recomendaciones:\n- Acuéstate boca abajo en banco de hiperextensiones.\n- Cruza los brazos sobre el pecho.\n- Flexiona hacia adelante y luego extiende la espalda.\n- Contrae los músculos lumbares en la posición alta.\n- Haz 3 series de 12-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 12,
                'calories_burned' => 85,
                'equipment' => 'Banco de hiperextensiones',
                'muscle_group' => 'Espalda',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Encogimientos de hombros',
                'description' => "Ejercicio específico para desarrollar y fortalecer los músculos del trapecio.\nInstrucciones y recomendaciones:\n- Mantente de pie con mancuernas a los costados.\n- Eleva los hombros hacia las orejas contrayendo el trapecio.\n- Mantén la posición por un segundo.\n- Desciende lentamente y repite.\n- Haz 3 series de 15-20 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 70,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Espalda',
                'intensity' => 'Baja',
                'is_active' => true,
            ],

            // ABDOMEN (10 ejercicios)
            [
                'name' => 'Plancha frontal',
                'description' => "Ejercicio isométrico fundamental para fortalecer todo el core y mejorar la estabilidad.\nInstrucciones y recomendaciones:\n- Apoya los antebrazos y pies en el suelo.\n- Mantén el cuerpo recto desde la cabeza hasta los talones.\n- Contrae el abdomen y glúteos durante todo el ejercicio.\n- Respira normalmente sin aguantar la respiración.\n- Mantén la posición durante 30-60 segundos.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 8,
                'calories_burned' => 80,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Crunch abdominal',
                'description' => "Ejercicio clásico que trabaja específicamente el recto abdominal.\nInstrucciones y recomendaciones:\n- Acuéstate boca arriba con rodillas flexionadas.\n- Coloca las manos detrás de la cabeza sin entrelazar los dedos.\n- Eleva los hombros del suelo contrayendo el abdomen.\n- Evita tirar del cuello con las manos.\n- Haz 3 series de 15-20 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 75,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Elevación de piernas',
                'description' => "Fortalece la parte inferior del abdomen y los flexores de cadera.\nInstrucciones y recomendaciones:\n- Acuéstate boca arriba con las piernas extendidas.\n- Mantén las manos a los costados para estabilidad.\n- Eleva las piernas hasta formar 90 grados con el torso.\n- Desciende lentamente sin tocar el suelo.\n- Haz 3 series de 10-15 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 90,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Plancha lateral',
                'description' => "Ejercicio unilateral que fortalece específicamente los oblicuos y el core lateral.\nInstrucciones y recomendaciones:\n- Acuéstate de lado apoyando el antebrazo en el suelo.\n- Eleva las caderas manteniendo el cuerpo recto.\n- Mantén la cabeza alineada con la columna.\n- Evita que las caderas se hundan.\n- Mantén 20-45 segundos por lado.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 10,
                'calories_burned' => 85,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Russian twist',
                'description' => "Ejercicio dinámico que trabaja oblicuos con rotación del tronco.\nInstrucciones y recomendaciones:\n- Siéntate con las rodillas flexionadas y pies ligeramente elevados.\n- Inclína el torso hacia atrás manteniendo la espalda recta.\n- Rota el torso de lado a lado tocando el suelo.\n- Mantén el abdomen contraído durante todo el movimiento.\n- Haz 3 series de 20-30 repeticiones (10-15 por lado).",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 95,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Mountain climbers',
                'description' => "Ejercicio cardiovascular que combina trabajo de core con cardio intenso.\nInstrucciones y recomendaciones:\n- Adopta posición de plancha con brazos extendidos.\n- Alterna llevando las rodillas al pecho rápidamente.\n- Mantén las caderas estables sin balancear.\n- Respira de manera controlada durante el ejercicio.\n- Haz 3 series de 20-30 segundos.",
                'category' => 'Cardio',
                'difficulty' => 'intermedio',
                'duration' => 8,
                'calories_burned' => 120,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Dead bug',
                'description' => "Ejercicio de control motor que enseña estabilización del core.\nInstrucciones y recomendaciones:\n- Acuéstate boca arriba con brazos extendidos hacia el techo.\n- Flexiona caderas y rodillas a 90 grados.\n- Extiende un brazo hacia atrás y la pierna opuesta hacia adelante.\n- Regresa lentamente a la posición inicial.\n- Haz 3 series de 8-10 repeticiones por lado.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 70,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Baja',
                'is_active' => true,
            ],
            [
                'name' => 'Bicicleta abdominal',
                'description' => "Ejercicio dinámico que combina flexión con rotación para trabajar todo el core.\nInstrucciones y recomendaciones:\n- Acuéstate boca arriba con manos detrás de la cabeza.\n- Alterna llevando el codo hacia la rodilla opuesta.\n- Extiende la pierna opuesta como si pedalearas.\n- Mantén el ritmo controlado sin tirar del cuello.\n- Haz 3 series de 20-30 repeticiones (10-15 por lado).",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 100,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Plancha con elevación de brazo',
                'description' => "Variante de plancha que añade inestabilidad y mayor activación del core.\nInstrucciones y recomendaciones:\n- Adopta posición de plancha sobre las manos.\n- Eleva un brazo hacia adelante manteniendo la posición.\n- Mantén las caderas estables sin rotar.\n- Alterna los brazos cada 5-10 segundos.\n- Haz 3 series de 30-45 segundos.",
                'category' => 'Equilibrio',
                'difficulty' => 'avanzado',
                'duration' => 10,
                'calories_burned' => 90,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'V-ups',
                'description' => "Ejercicio avanzado que trabaja simultáneamente la parte superior e inferior del abdomen.\nInstrucciones y recomendaciones:\n- Acuéstate boca arriba con brazos y piernas extendidos.\n- Eleva simultáneamente el torso y las piernas formando una V.\n- Toca los pies con las manos en la posición alta.\n- Desciende controladamente sin tocar completamente el suelo.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 10,
                'calories_burned' => 110,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Abdomen',
                'intensity' => 'Alta',
                'is_active' => true,
            ],

            // TODO EL CUERPO (10 ejercicios)
            [
                'name' => 'Burpees',
                'description' => "Ejercicio completo que combina cardio y fuerza trabajando todo el cuerpo intensamente.\nInstrucciones y recomendaciones:\n- Comienza de pie, luego baja a cuclillas apoyando las manos.\n- Salta hacia atrás adoptando posición de plancha.\n- Realiza una flexión y salta para regresar a cuclillas.\n- Salta hacia arriba con los brazos extendidos.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Cardio',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 180,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Muy alta',
                'is_active' => true,
            ],
            [
                'name' => 'Plancha con salto',
                'description' => "Combina plancha isométrica con movimiento explosivo de piernas.\nInstrucciones y recomendaciones:\n- Adopta posición de plancha con brazos extendidos.\n- Salta llevando los pies hacia las manos en cuclillas.\n- Salta nuevamente para regresar a posición de plancha.\n- Mantén el core activado durante todo el movimiento.\n- Haz 3 series de 10-15 repeticiones.",
                'category' => 'Cardio',
                'difficulty' => 'intermedio',
                'duration' => 10,
                'calories_burned' => 140,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Thruster con mancuernas',
                'description' => "Movimiento compuesto que combina sentadilla frontal con press de hombros.\nInstrucciones y recomendaciones:\n- Sostén mancuernas a la altura de los hombros.\n- Realiza una sentadilla profunda manteniendo el pecho erguido.\n- Al subir, empuja las mancuernas sobre la cabeza.\n- Desciende las mancuernas mientras bajas a sentadilla.\n- Haz 3 series de 8-12 repeticiones.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 18,
                'calories_burned' => 160,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Bear crawl',
                'description' => "Movimiento cuadrúpedo que fortalece core, hombros y mejora la coordinación.\nInstrucciones y recomendaciones:\n- Adopta posición cuadrúpeda con rodillas elevadas del suelo.\n- Camina hacia adelante moviendo mano y pie opuestos.\n- Mantén las rodillas cerca del suelo pero sin tocar.\n- Mantén la espalda plana y el core activado.\n- Camina 10-15 pasos hacia adelante y hacia atrás.",
                'category' => 'Fuerza',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 130,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Swing con kettlebell',
                'description' => "Ejercicio explosivo que desarrolla potencia y resistencia cardiovascular.\nInstrucciones y recomendaciones:\n- Sostén la kettlebell con ambas manos entre las piernas.\n- Flexiona las caderas hacia atrás manteniendo la espalda recta.\n- Impulsa las caderas hacia adelante elevando la kettlebell.\n- Deja que la kettlebell descienda entre las piernas.\n- Haz 3 series de 15-20 repeticiones.",
                'category' => 'Cardio',
                'difficulty' => 'intermedio',
                'duration' => 15,
                'calories_burned' => 170,
                'equipment' => 'Kettlebell',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Turkish get-up',
                'description' => "Movimiento complejo que desarrolla fuerza, movilidad y estabilidad en todo el cuerpo.\nInstrucciones y recomendaciones:\n- Acuéstate con una kettlebell extendida sobre el pecho.\n- Levántate paso a paso hasta quedar de pie.\n- Mantén la kettlebell estable durante todo el movimiento.\n- Regresa a la posición inicial por el mismo camino.\n- Haz 2-3 repeticiones por lado.",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 20,
                'calories_burned' => 150,
                'equipment' => 'Kettlebell o mancuerna',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Man maker',
                'description' => "Combinación de burpee con remo que trabaja intensamente todo el cuerpo.\nInstrucciones y recomendaciones:\n- Comienza con mancuernas en el suelo en posición de flexión.\n- Realiza un remo con cada brazo alternadamente.\n- Salta los pies hacia las manos en cuclillas.\n- Levántate y haz un press de hombros.\n- Haz 3 series de 6-10 repeticiones.",
                'category' => 'Cardio',
                'difficulty' => 'avanzado',
                'duration' => 15,
                'calories_burned' => 200,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Muy alta',
                'is_active' => true,
            ],
            [
                'name' => 'Crawling lateral',
                'description' => "Movimiento lateral en cuadrupedia que mejora coordinación y fuerza.\nInstrucciones y recomendaciones:\n- Adopta posición cuadrúpeda con rodillas elevadas.\n- Muévete lateralmente moviendo mano y pie del mismo lado.\n- Mantén las rodillas cerca del suelo sin tocar.\n- Cambia de dirección después de 5-8 pasos.\n- Haz 2-3 series de desplazamientos laterales.",
                'category' => 'Fuerza',
                'difficulty' => 'principiante',
                'duration' => 10,
                'calories_burned' => 100,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Moderada',
                'is_active' => true,
            ],
            [
                'name' => 'Renegade row',
                'description' => "Combina plancha con remo unilateral, desafiando estabilidad y fuerza.\nInstrucciones y recomendaciones:\n- Adopta posición de plancha apoyando las manos en mancuernas.\n- Mantén la posición mientras realizas un remo con un brazo.\n- Evita rotar las caderas durante el remo.\n- Alterna los brazos manteniendo la estabilidad.\n- Haz 3 series de 8-12 repeticiones (4-6 por brazo).",
                'category' => 'Fuerza',
                'difficulty' => 'avanzado',
                'duration' => 15,
                'calories_burned' => 145,
                'equipment' => 'Mancuernas',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
            [
                'name' => 'Squat thrust',
                'description' => "Movimiento explosivo que combina sentadilla con salto vertical.\nInstrucciones y recomendaciones:\n- Comienza en posición de cuclillas con manos en el suelo.\n- Salta hacia atrás adoptando posición de plancha.\n- Salta nuevamente para regresar a cuclillas.\n- Salta verticalmente con los brazos extendidos hacia arriba.\n- Haz 3 series de 10-15 repeticiones.",
                'category' => 'Cardio',
                'difficulty' => 'intermedio',
                'duration' => 12,
                'calories_burned' => 155,
                'equipment' => 'Peso corporal',
                'muscle_group' => 'Todo el cuerpo',
                'intensity' => 'Alta',
                'is_active' => true,
            ],
        ];

        foreach ($exercises as $exerciseData) {
            $exercise = Exercise::create($exerciseData);
            
            // Crear una imagen por defecto para cada ejercicio
            ExerciseImage::create([
                'exercise_id' => $exercise->id,
                'path' => 'test',
                'position' => 0,
            ]);
        }
    }
}