<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Food;
use App\Models\FoodImage;

class FoodSeeder extends Seeder
{
    public function run()
    {
        $foods = [
            // DESAYUNO (10 comidas)
            [
                'name' => 'Tostadas integrales con palta',
                'description' => 'Desayuno nutritivo y saciante rico en grasas saludables y fibra.',
                'ingredients' => "Pan integral\nPalta madura\nTomate cherry\nSal marina\nPimienta negra\nLimón",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 10,
                'calories_per_serving' => 320,
                'protein' => 8,
                'carbohydrates' => 35,
                'fats' => 18,
                'servings' => 1,
                'preparation' => "Tuesta el pan integral hasta dorar.\nMachaca la palta con tenedor.\nAñade sal, pimienta y unas gotas de limón.\nExtiende sobre las tostadas.\nDecora con tomate cherry cortado.",
                'is_active' => true,
            ],
            [
                'name' => 'Yogur griego con granola casera',
                'description' => 'Desayuno proteico con probióticos naturales y cereales crujientes.',
                'ingredients' => "Yogur griego natural\nAvena en hojuelas\nNueces picadas\nMiel pura\nSemillas de chía\nFrutos rojos",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 8,
                'calories_per_serving' => 380,
                'protein' => 20,
                'carbohydrates' => 42,
                'fats' => 15,
                'servings' => 1,
                'preparation' => "Mezcla avena, nueces y semillas en un bowl.\nAñade una cucharada de miel y mezcla.\nSirve el yogur en un bowl.\nCubre con la granola casera.\nDecora con frutos rojos frescos.",
                'is_active' => true,
            ],
            [
                'name' => 'Smoothie verde energético',
                'description' => 'Batido nutritivo lleno de vitaminas y minerales para empezar el día.',
                'ingredients' => "Espinacas frescas\nPlátano maduro\nManzana verde\nJengibre fresco\nAgua de coco\nSemillas de linaza",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 5,
                'calories_per_serving' => 280,
                'protein' => 6,
                'carbohydrates' => 58,
                'fats' => 4,
                'servings' => 1,
                'preparation' => "Lava bien las espinacas.\nPela el plátano y corta la manzana.\nAñade todos los ingredientes a la licuadora.\nBate hasta obtener consistencia cremosa.\nSirve inmediatamente bien frío.",
                'is_active' => true,
            ],
            [
                'name' => 'Huevos revueltos con vegetales',
                'description' => 'Desayuno proteico colorido con vegetales frescos y nutritivos.',
                'ingredients' => "Huevos frescos\nPimientos de colores\nCebolla morada\nEspinacas baby\nQueso fresco\nAceite de oliva",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 12,
                'calories_per_serving' => 340,
                'protein' => 22,
                'carbohydrates' => 8,
                'fats' => 24,
                'servings' => 1,
                'preparation' => "Pica finamente los vegetales.\nSaltea en aceite hasta dorar.\nBate los huevos con sal y pimienta.\nAñade huevos a los vegetales.\nRevuelve suavemente hasta cuajar.\nAcompaña con queso fresco.",
                'is_active' => true,
            ],
            [
                'name' => 'Pancakes de avena y plátano',
                'description' => 'Versión saludable de los pancakes tradicionales, naturalmente dulces.',
                'ingredients' => "Avena en hojuelas\nPlátanos maduros\nHuevos\nCanela en polvo\nPolvo de hornear\nLeche vegetal",
                'category' => 'Desayuno',
                'difficulty' => 'intermedio',
                'preparation_time' => 20,
                'calories_per_serving' => 365,
                'protein' => 14,
                'carbohydrates' => 52,
                'fats' => 12,
                'servings' => 2,
                'preparation' => "Tritura la avena hasta obtener harina.\nMachaca los plátanos hasta formar puré.\nMezcla todos los ingredientes secos.\nAñade ingredientes húmedos y mezcla.\nCocina en sartén antiadherente.\nSirve calientes con frutas frescas.",
                'is_active' => true,
            ],
            [
                'name' => 'Chia pudding con frutas',
                'description' => 'Pudín cremoso rico en omega-3 y fibra, preparado la noche anterior.',
                'ingredients' => "Semillas de chía\nLeche de almendras\nMiel natural\nVainilla\nFrutas de temporada\nCoco rallado",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 5,
                'calories_per_serving' => 290,
                'protein' => 9,
                'carbohydrates' => 35,
                'fats' => 14,
                'servings' => 1,
                'preparation' => "Mezcla chía con leche de almendras.\nAñade miel y vainilla.\nRefrigera durante la noche.\nRevuelve antes de servir.\nDecora con frutas frescas.\nEspolvorea coco rallado encima.",
                'is_active' => true,
            ],
            [
                'name' => 'Tazón de açaí casero',
                'description' => 'Bowl antioxidante y refrescante perfecto para mañanas calurosas.',
                'ingredients' => "Pulpa de açaí congelada\nPlátano congelado\nGranola natural\nFrutos rojos\nCoco laminado\nMiel",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 8,
                'calories_per_serving' => 350,
                'protein' => 8,
                'carbohydrates' => 68,
                'fats' => 10,
                'servings' => 1,
                'preparation' => "Procesa açaí con plátano congelado.\nBate hasta obtener consistencia cremosa.\nSirve en bowl frío.\nDecora con granola en líneas.\nAñade frutos rojos y coco.\nRocía miel al gusto.",
                'is_active' => true,
            ],
            [
                'name' => 'Muesli casero con frutos secos',
                'description' => 'Mezcla nutritiva de cereales y frutos secos para un desayuno completo.',
                'ingredients' => "Avena tradicional\nAlmendras fileteadas\nPasas sin azúcar\nSemillas de girasol\nYogur natural\nMiel pura",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 5,
                'calories_per_serving' => 410,
                'protein' => 16,
                'carbohydrates' => 58,
                'fats' => 14,
                'servings' => 1,
                'preparation' => "Mezcla todos los ingredientes secos.\nSirve en bowl con yogur natural.\nAñade miel al gusto.\nDeja reposar 2 minutos para hidratar.\nMezcla bien antes de consumir.",
                'is_active' => true,
            ],
            [
                'name' => 'Batido de proteína natural',
                'description' => 'Smoothie post-entrenamiento rico en proteínas naturales.',
                'ingredients' => "Leche de almendras\nProteína en polvo natural\nMantequilla de almendras\nPlátano\nEspinacas\nHielo",
                'category' => 'Desayuno',
                'difficulty' => 'fácil',
                'preparation_time' => 5,
                'calories_per_serving' => 385,
                'protein' => 28,
                'carbohydrates' => 32,
                'fats' => 16,
                'servings' => 1,
                'preparation' => "Combina todos los ingredientes en licuadora.\nBate hasta obtener textura suave.\nAjusta consistencia con más leche si necesario.\nSirve inmediatamente.\nDecora con almendras fileteadas.",
                'is_active' => true,
            ],
            [
                'name' => 'Tortilla francesa de hierbas',
                'description' => 'Tortilla esponjosa aromatizada con hierbas frescas del huerto.',
                'ingredients' => "Huevos frescos\nPerejil fresco\nCebollino\nBasílico\nQueso de cabra\nAceite de oliva",
                'category' => 'Desayuno',
                'difficulty' => 'intermedio',
                'preparation_time' => 15,
                'calories_per_serving' => 310,
                'protein' => 20,
                'carbohydrates' => 4,
                'fats' => 24,
                'servings' => 1,
                'preparation' => "Pica finamente todas las hierbas.\nBate huevos con las hierbas.\nCalienta aceite en sartén antiadherente.\nVierte mezcla y cocina a fuego medio.\nAñade queso de cabra desmigajado.\nDobla por la mitad y sirve caliente.",
                'is_active' => true,
            ],
            [
                'name' => 'Sopaipillas integrales horneadas',
                'description' => 'Versión saludable del clásico chileno, horneadas en lugar de fritas.',
                'ingredients' => "Harina integral\nZapallo cocido\nAceite de oliva\nSal\nPolvos de hornear\nComino\nPebre casero",
                'category' => 'Desayuno',
                'difficulty' => 'intermedio',
                'preparation_time' => 45,
                'calories_per_serving' => 180,
                'protein' => 5,
                'carbohydrates' => 32,
                'fats' => 4,
                'servings' => 6,
                'preparation' => "Mezcla zapallo pisado con harina integral.\nAñade aceite, sal y polvos de hornear.\nAmasa hasta formar masa suave.\nEstira y corta en círculos.\nHaz hoyo en el centro.\nHornea a 200°C hasta dorar.\nSirve con pebre casero.",
                'is_active' => true,
            ],

            // ALMUERZO (10 comidas)
            [
                'name' => 'Ensalada de garbanzos mediterránea',
                'description' => 'Ensalada completa y nutritiva con sabores mediterráneos frescos.',
                'ingredients' => "Garbanzos cocidos\nPepino\nTomates cherry\nCebolla morada\nQueso feta\nAceitunas negras\nAceite de oliva\nLimón",
                'category' => 'Almuerzo',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 420,
                'protein' => 18,
                'carbohydrates' => 45,
                'fats' => 20,
                'servings' => 2,
                'preparation' => "Escurre y enjuaga los garbanzos.\nCorta pepino y tomates en cubos.\nPica finamente la cebolla morada.\nMezcla todos los vegetales en bowl.\nAliña con aceite, limón, sal y pimienta.\nDecora con queso feta y aceitunas.",
                'is_active' => true,
            ],
            [
                'name' => 'Wrap de pollo y vegetales',
                'description' => 'Envuelto nutritivo con proteína magra y vegetales crujientes.',
                'ingredients' => "Tortilla integral\nPechuga de pollo\nLechuga fresca\nTomate\nPalta\nYogur griego\nMostaza dijon",
                'category' => 'Almuerzo',
                'difficulty' => 'fácil',
                'preparation_time' => 20,
                'calories_per_serving' => 380,
                'protein' => 32,
                'carbohydrates' => 35,
                'fats' => 14,
                'servings' => 1,
                'preparation' => "Cocina la pechuga de pollo sazonada.\nCorta en tiras cuando esté fría.\nExtiende yogur mezclado con mostaza en tortilla.\nAñade lechuga, tomate y palta.\nColoca el pollo encima.\nEnvuelve firmemente y corta por la mitad.",
                'is_active' => true,
            ],
            [
                'name' => 'Bowl de quinoa con verduras asadas',
                'description' => 'Plato completo con súper cereal y vegetales caramelizados al horno.',
                'ingredients' => "Quinoa tricolor\nCalabacín\nPimientos rojos\nBrócoli\nZanahoria\nAceite de oliva\nTahini\nLimón",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 35,
                'calories_per_serving' => 390,
                'protein' => 14,
                'carbohydrates' => 58,
                'fats' => 12,
                'servings' => 2,
                'preparation' => "Cocina quinoa según instrucciones del paquete.\nCorta vegetales en trozos uniformes.\nRocea con aceite y sazona.\nAsa en horno a 200°C por 25 minutos.\nMezcla tahini con limón para aderezo.\nSirve quinoa con vegetales y salsa.",
                'is_active' => true,
            ],
            [
                'name' => 'Sopa de lentejas especiada',
                'description' => 'Sopa reconfortante y nutritiva con especias aromáticas.',
                'ingredients' => "Lentejas rojas\nCebolla\nAjo\nJengibre\nCúrcuma\nComino\nCaldo de vegetales\nEspinacas",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 30,
                'calories_per_serving' => 280,
                'protein' => 16,
                'carbohydrates' => 48,
                'fats' => 3,
                'servings' => 4,
                'preparation' => "Sofríe cebolla, ajo y jengibre picados.\nAñade especias y cocina 1 minuto.\nIncorpora lentejas y caldo.\nCocina 20 minutos hasta que estén tiernas.\nAñade espinacas al final.\nAjusta sazón y sirve caliente.",
                'is_active' => true,
            ],
            [
                'name' => 'Pasta integral con pesto de albahaca',
                'description' => 'Pasta nutritiva con salsa verde casera llena de antioxidantes.',
                'ingredients' => "Pasta integral\nAlbahaca fresca\nPiñones\nAjo\nQueso parmesano\nAceite de oliva\nTomates cherry",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 25,
                'calories_per_serving' => 450,
                'protein' => 16,
                'carbohydrates' => 52,
                'fats' => 22,
                'servings' => 2,
                'preparation' => "Cocina pasta según instrucciones.\nProcesa albahaca, piñones, ajo y queso.\nAñade aceite gradualmente hasta formar pasta.\nMezcla pasta caliente con pesto.\nDecora con tomates cherry cortados.\nSirve inmediatamente con queso extra.",
                'is_active' => true,
            ],
            [
                'name' => 'Buddha bowl vegano',
                'description' => 'Plato equilibrado con proteínas vegetales y colores vibrantes.',
                'ingredients' => "Arroz integral\nTofu marinado\nBrotes de soja\nEdamame\nZanahoria rallada\nRemolacha\nSésamo\nSalsa de soja",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 40,
                'calories_per_serving' => 400,
                'protein' => 18,
                'carbohydrates' => 55,
                'fats' => 14,
                'servings' => 2,
                'preparation' => "Cocina arroz integral.\nMarina tofu cortado en cubos.\nSaltea tofu hasta dorar.\nCocina edamame al vapor.\nArreg la todos los ingredientes en bowl.\nRocea con salsa de soja y sésamo.",
                'is_active' => true,
            ],
            [
                'name' => 'Hamburguesa de porotos negros',
                'description' => 'Alternativa vegetal rica en proteínas y fibra.',
                'ingredients' => "Porotos negros\nAvena\nCebolla\nAjo\nComino\nPimentón\nPan integral\nPalta\nTomate",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 30,
                'calories_per_serving' => 385,
                'protein' => 16,
                'carbohydrates' => 62,
                'fats' => 10,
                'servings' => 2,
                'preparation' => "Machaca porotos dejando algunos enteros.\nMezcla con avena, cebolla y especias.\nForma hamburguesas y refrigera 30 min.\nCocina en sartén hasta dorar.\nTuesta el pan integral.\nArma hamburguesa con palta y tomate.",
                'is_active' => true,
            ],
            [
                'name' => 'Risotto de champiñones',
                'description' => 'Arroz cremoso con hongos aromáticos y hierbas frescas.',
                'ingredients' => "Arroz arborio\nChampiñones mixtos\nCaldo de vegetales\nCebolla\nVino blanco\nQueso parmesano\nPerejil",
                'category' => 'Almuerzo',
                'difficulty' => 'difícil',
                'preparation_time' => 45,
                'calories_per_serving' => 420,
                'protein' => 12,
                'carbohydrates' => 68,
                'fats' => 10,
                'servings' => 2,
                'preparation' => "Saltea champiñones hasta dorar.\nSofríe cebolla picada.\nAñade arroz y tuesta 2 minutos.\nAgrega vino y deja evaporar.\nIncorpora caldo caliente de a poco.\nRevuelve constantemente 20 minutos.\nTermina con queso y perejil.",
                'is_active' => true,
            ],
            [
                'name' => 'Ensalada de atún y porotos blancos',
                'description' => 'Ensalada proteica mediterránea perfecta para días calurosos.',
                'ingredients' => "Atún en agua\nPorotos blancos\nTomate\nCebolla morada\nPimiento\nAceitunas\nVinagre balsámico\nAceite de oliva",
                'category' => 'Almuerzo',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 350,
                'protein' => 28,
                'carbohydrates' => 32,
                'fats' => 12,
                'servings' => 2,
                'preparation' => "Escurre atún y porotos.\nCorta vegetales en cubos pequeños.\nMezcla todos los ingredientes en bowl.\nAliña con vinagre y aceite.\nSazona con sal, pimienta y hierbas.\nDeja marinar 10 minutos antes de servir.",
                'is_active' => true,
            ],
            [
                'name' => 'Curry de garbanzos y espinacas',
                'description' => 'Plato aromático lleno de especias y vegetales nutritivos.',
                'ingredients' => "Garbanzos cocidos\nEspinacas frescas\nLeche de coco\nCebolla\nAjo\nJengibre\nCurry en polvo\nComino",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 25,
                'calories_per_serving' => 320,
                'protein' => 14,
                'carbohydrates' => 38,
                'fats' => 14,
                'servings' => 3,
                'preparation' => "Sofríe cebolla, ajo y jengibre.\nAñade especias y cocina 1 minuto.\nIncorpora garbanzos y leche de coco.\nCocina 15 minutos a fuego medio.\nAñade espinacas al final.\nSirve con arroz integral.",
                'is_active' => true,
            ],
            [
                'name' => 'Cazuela de pollo con verduras',
                'description' => 'Plato tradicional chileno nutritivo con pollo y vegetales de temporada.',
                'ingredients' => "Presa de pollo\nZapallo\nChoclo\nZanahoria\nPorotos verdes\nPapas\nCebolla\nArroz\nCilantro",
                'category' => 'Almuerzo',
                'difficulty' => 'intermedio',
                'preparation_time' => 60,
                'calories_per_serving' => 420,
                'protein' => 28,
                'carbohydrates' => 45,
                'fats' => 12,
                'servings' => 4,
                'preparation' => "Dora las presas de pollo en olla.\nAñade agua y cebolla, cocina 30 min.\nIncorpora papas y zanahoria.\nAñade zapallo y porotos verdes.\nIncorpora choclo y arroz.\nCocina hasta que todo esté tierno.\nDecora con cilantro fresco.",
                'is_active' => true,
            ],

            // CENA (10 comidas)
            [
                'name' => 'Pescado al vapor con vegetales',
                'description' => 'Preparación ligera y saludable que conserva todos los nutrientes.',
                'ingredients' => "Filete de pescado blanco\nCalabacín\nZanahoria\nBrócoli\nJengibre\nLimón\nSalsa de soja\nSésamo",
                'category' => 'Cena',
                'difficulty' => 'intermedio',
                'preparation_time' => 25,
                'calories_per_serving' => 280,
                'protein' => 35,
                'carbohydrates' => 15,
                'fats' => 8,
                'servings' => 2,
                'preparation' => "Prepara vaporera con agua hirviendo.\nCorta vegetales en trozos uniformes.\nSazona pescado con jengibre y limón.\nCocina vegetales al vapor 10 minutos.\nAñade pescado y cocina 8 minutos más.\nSirve con salsa de soja y sésamo.",
                'is_active' => true,
            ],
            [
                'name' => 'Ensalada de pollo tibia',
                'description' => 'Ensalada reconfortante con proteína caliente y vegetales frescos.',
                'ingredients' => "Pechuga de pollo\nMezcla de lechugas\nTomates cherry\nPepino\nQueso de cabra\nNueces\nVinagreta de mostaza",
                'category' => 'Cena',
                'difficulty' => 'fácil',
                'preparation_time' => 20,
                'calories_per_serving' => 340,
                'protein' => 32,
                'carbohydrates' => 12,
                'fats' => 20,
                'servings' => 2,
                'preparation' => "Cocina pechuga de pollo sazonada.\nCorta en tiras mientras está tibia.\nPrepara base de lechugas mixtas.\nAñade tomates y pepino cortados.\nColoca pollo tibio encima.\nDecora con queso de cabra y nueces.\nAliña con vinagreta.",
                'is_active' => true,
            ],
            [
                'name' => 'Sopa de miso con tofu',
                'description' => 'Sopa japonesa nutritiva y reconfortante, rica en probióticos.',
                'ingredients' => "Pasta de miso\nTofu sedoso\nCebollín\nAlgas wakame\nCaldo dashi\nShiitake\nSoja en grano",
                'category' => 'Cena',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 180,
                'protein' => 12,
                'carbohydrates' => 8,
                'fats' => 8,
                'servings' => 2,
                'preparation' => "Hidrata algas en agua tibia.\nCorta tofu en cubos pequeños.\nCalienta caldo dashi suavemente.\nDisuelve miso en un poco de caldo.\nAñade tofu, algas y champiñones.\nDecora con cebollín picado.\nSirve inmediatamente.",
                'is_active' => true,
            ],
            [
                'name' => 'Tortilla de verduras al horno',
                'description' => 'Tortilla esponjosa horneada con vegetales de temporada.',
                'ingredients' => "Huevos\nCalabacín\nPimiento rojo\nCebolla\nEspinacas\nQueso fresco\nHierbas aromáticas\nAceite de oliva",
                'category' => 'Cena',
                'difficulty' => 'intermedio',
                'preparation_time' => 30,
                'calories_per_serving' => 260,
                'protein' => 18,
                'carbohydrates' => 12,
                'fats' => 16,
                'servings' => 4,
                'preparation' => "Precalienta horno a 180°C.\nSaltea vegetales hasta que estén tiernos.\nBate huevos con sal, pimienta y hierbas.\nMezcla huevos con vegetales.\nVierte en molde engrasado.\nEsparce queso fresco encima.\nHornea 20 minutos hasta dorar.",
                'is_active' => true,
            ],
            [
                'name' => 'Tacos de pescado con repollo',
                'description' => 'Tacos ligeros con pescado fresco y ensalada crujiente.',
                'ingredients' => "Tortillas de choclo\nPescado blanco\nRepollo morado\nLimón\nCilantro\nYogur griego\nPimiento jalapeño\nRábanos",
                'category' => 'Cena',
                'difficulty' => 'fácil',
                'preparation_time' => 20,
                'calories_per_serving' => 290,
                'protein' => 24,
                'carbohydrates' => 32,
                'fats' => 8,
                'servings' => 2,
                'preparation' => "Sazona y cocina pescado hasta que se desmenuce.\nCorta repollo en juliana fina.\nMezcla con limón y cilantro.\nPrepara crema con yogur y jalapeño.\nCalienta tortillas en comal.\nArma tacos con pescado y repollo.\nDecora con rábanos en rodajas.",
                'is_active' => true,
            ],
            [
                'name' => 'Salteado de tofu con verduras',
                'description' => 'Plato asiático colorido y nutritivo cocinado a fuego alto.',
                'ingredients' => "Tofu firme\nPimientos de colores\nZanahoria\nBrotes de soja\nAjo\nJengibre\nSalsa de soja\nAceite de sésamo",
                'category' => 'Cena',
                'difficulty' => 'fácil',
                'preparation_time' => 18,
                'calories_per_serving' => 250,
                'protein' => 16,
                'carbohydrates' => 18,
                'fats' => 14,
                'servings' => 2,
                'preparation' => "Corta tofu en cubos y dora en wok.\nRetira y reserva el tofu.\nSaltea ajo y jengibre aromáticamente.\nAñade vegetales por orden de cocción.\nIncorpora tofu al final.\nSazona con salsas.\nSirve inmediatamente sobre arroz.",
                'is_active' => true,
            ],
            [
                'name' => 'Crema de calabaza asada',
                'description' => 'Sopa cremosa y aromática perfecta para noches frescas.',
                'ingredients' => "Calabaza moscada\nCebolla\nAjo\nJengibre\nLeche de coco\nCaldo de vegetales\nNuez moscada\nSemillas de calabaza",
                'category' => 'Cena',
                'difficulty' => 'intermedio',
                'preparation_time' => 40,
                'calories_per_serving' => 220,
                'protein' => 6,
                'carbohydrates' => 28,
                'fats' => 10,
                'servings' => 4,
                'preparation' => "Asa calabaza cortada en horno 25 minutos.\nSofríe cebolla, ajo y jengibre.\nAñade calabaza asada y caldo.\nCocina 15 minutos hasta tierna.\nTritura hasta obtener crema suave.\nIncorpora leche de coco.\nDecora con semillas tostadas.",
                'is_active' => true,
            ],
            [
                'name' => 'Pollo a la plancha con hierbas',
                'description' => 'Proteína magra aromática con marinado de hierbas mediterráneas.',
                'ingredients' => "Pechuga de pollo\nRomero fresco\nTomillo\nLimón\nAjo\nAceite de oliva\nVerduras al vapor",
                'category' => 'Cena',
                'difficulty' => 'fácil',
                'preparation_time' => 25,
                'calories_per_serving' => 320,
                'protein' => 38,
                'carbohydrates' => 8,
                'fats' => 14,
                'servings' => 2,
                'preparation' => "Marina pollo con hierbas, ajo y limón.\nDeja reposar al menos 30 minutos.\nCocina en plancha caliente 6 minutos por lado.\nDeja reposar antes de cortar.\nPrepara verduras al vapor como acompañamiento.\nSirve con gotas de limón fresco.",
                'is_active' => true,
            ],
            [
                'name' => 'Ensalada tibia de lentejas',
                'description' => 'Ensalada nutritiva y saciante con legumbres y vegetales asados.',
                'ingredients' => "Lentejas verdes\nRemolacha\nZanahoria\nCebolla morada\nQueso feta\nNueces\nVinagre balsámico\nAceite de oliva",
                'category' => 'Cena',
                'difficulty' => 'intermedio',
                'preparation_time' => 35,
                'calories_per_serving' => 350,
                'protein' => 16,
                'carbohydrates' => 42,
                'fats' => 14,
                'servings' => 2,
                'preparation' => "Cocina lentejas hasta que estén tiernas.\nAsa remolacha y zanahoria en horno.\nCorta cebolla en medias lunas finas.\nMezcla lentejas tibias con vegetales.\nAliña con vinagre y aceite.\nDecora con queso feta y nueces.",
                'is_active' => true,
            ],
            [
                'name' => 'Calabacín relleno de quinoa',
                'description' => 'Verdura rellena con súper cereal y vegetales aromáticos.',
                'ingredients' => "Calabacín grande\nQuinoa\nTomate\nCebolla\nPimiento\nQueso rallado\nHierbas frescas\nCaldo de vegetales",
                'category' => 'Cena',
                'difficulty' => 'intermedio',
                'preparation_time' => 45,
                'calories_per_serving' => 290,
                'protein' => 12,
                'carbohydrates' => 38,
                'fats' => 10,
                'servings' => 2,
                'preparation' => "Ahue ca calabacín reservando pulpa.\nSofríe cebolla, pimiento y pulpa.\nAñade quinoa cocida y tomate.\nSazona con hierbas frescas.\nRellena calabacín con mezcla.\nCubre con queso rallado.\nHornea 25 minutos hasta dorar.",
                'is_active' => true,
            ],
            [
                'name' => 'Charquicán de verduras',
                'description' => 'Plato tradicional chileno vegetariano con papas y verduras picadas.',
                'ingredients' => "Papas\nZapallo\nPorotos verdes\nChoclo\nZanahoria\nCebolla\nAjo\nMerkén\nHuevo\nCilantro",
                'category' => 'Cena',
                'difficulty' => 'fácil',
                'preparation_time' => 35,
                'calories_per_serving' => 280,
                'protein' => 12,
                'carbohydrates' => 48,
                'fats' => 6,
                'servings' => 3,
                'preparation' => "Sofríe cebolla y ajo hasta dorar.\nAñade papas en cubos y zapallo.\nIncorpora zanahoria y porotos verdes.\nAñade choclo y sazona con merkén.\nCocina hasta que las papas se deshagan.\nSirve coronado con huevo frito.\nDecora with cilantro picado.",
                'is_active' => true,
            ],

            // SNACK (10 comidas)
            [
                'name' => 'Hummus con bastones de vegetales',
                'description' => 'Dip cremoso de garbanzos acompañado de vegetales crujientes.',
                'ingredients' => "Garbanzos cocidos\nTahini\nLimón\nAjo\nZanahoria\nApio\nPimiento\nPepino",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 180,
                'protein' => 8,
                'carbohydrates' => 22,
                'fats' => 8,
                'servings' => 3,
                'preparation' => "Procesa garbanzos con tahini y limón.\nAñade ajo, sal y pimienta al gusto.\nAjusta consistencia con agua.\nCorta vegetales en bastones uniformes.\nSirve hummus en bowl central.\nAcompaña con vegetales frescos.",
                'is_active' => true,
            ],
            [
                'name' => 'Nueces con miel y canela',
                'description' => 'Snack energético dulce con grasas saludables y especias.',
                'ingredients' => "Nueces mixtas\nMiel pura\nCanela en polvo\nSal marina\nRomero fresco",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 10,
                'calories_per_serving' => 220,
                'protein' => 6,
                'carbohydrates' => 12,
                'fats' => 18,
                'servings' => 2,
                'preparation' => "Tuesta nueces en sartén sin aceite.\nAñade miel y canela mientras están calientes.\nMezcla hasta cubrir uniformemente.\nEspolvorea pizca de sal marina.\nDeja enfriar antes de servir.\nGuarda en recipiente hermético.",
                'is_active' => true,
            ],
            [
                'name' => 'Smoothie bowl de frutos rojos',
                'description' => 'Bowl cremoso y colorido rico en antioxidantes naturales.',
                'ingredients' => "Frutos rojos congelados\nPlátano\nYogur griego\nGranola\nSemillas de chía\nMiel",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 8,
                'calories_per_serving' => 250,
                'protein' => 12,
                'carbohydrates' => 38,
                'fats' => 6,
                'servings' => 1,
                'preparation' => "Procesa frutos congelados con plátano.\nAñade yogur hasta obtener consistencia cremosa.\nSirve en bowl frío.\nDecora con granola en líneas.\nEspolvorea semillas de chía.\nRocía miel al gusto.",
                'is_active' => true,
            ],
            [
                'name' => 'Tostadas de palta con semillas',
                'description' => 'Snack nutritivo con grasas saludables y texturas crujientes.',
                'ingredients' => "Pan integral\nPalta madura\nSemillas de girasol\nSemillas de calabaza\nLimón\nSal marina\nPimienta roja",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 8,
                'calories_per_serving' => 280,
                'protein' => 8,
                'carbohydrates' => 25,
                'fats' => 18,
                'servings' => 1,
                'preparation' => "Tuesta pan hasta dorar.\nMachaca palta con tenedor.\nAñade limón, sal y pimienta.\nExtiende sobre tostada.\nEspolvorea semillas mixtas.\nSirve inmediatamente.",
                'is_active' => true,
            ],
            [
                'name' => 'Energy balls de dátiles',
                'description' => 'Bolitas energéticas naturalmente dulces sin azúcar refinada.',
                'ingredients' => "Dátiles sin hueso\nAlmendras\nCoco rallado\nSemillas de chía\nVainilla\nCacao en polvo",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 160,
                'protein' => 4,
                'carbohydrates' => 22,
                'fats' => 8,
                'servings' => 6,
                'preparation' => "Remoja dátiles hasta ablandar.\nProcesa con almendras hasta formar pasta.\nAñade coco, chía y vainilla.\nForma bolitas con las manos.\nRueda en cacao en polvo.\nRefrigera 30 minutos antes de servir.",
                'is_active' => true,
            ],
            [
                'name' => 'Yogur con frutas y granola',
                'description' => 'Snack cremoso con probióticos y texturas contrastantes.',
                'ingredients' => "Yogur natural\nFrutas de temporada\nGranola casera\nMiel\nAlmendras laminadas\nMenta fresca",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 5,
                'calories_per_serving' => 200,
                'protein' => 10,
                'carbohydrates' => 28,
                'fats' => 6,
                'servings' => 1,
                'preparation' => "Sirve yogur en bowl.\nAñade frutas cortadas encima.\nEspolvorea granola generosamente.\nDecora con almendras laminadas.\nRocía miel al gusto.\nAdorna con hojas de menta.",
                'is_active' => true,
            ],
            [
                'name' => 'Chips de kale horneados',
                'description' => 'Alternativa saludable a las papas fritas, crujiente y nutritiva.',
                'ingredients' => "Kale fresco\nAceite de oliva\nSal marina\nLevadura nutricional\nPimentón dulce\nAjo en polvo",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 20,
                'calories_per_serving' => 80,
                'protein' => 4,
                'carbohydrates' => 8,
                'fats' => 4,
                'servings' => 2,
                'preparation' => "Lava y seca bien las hojas de kale.\nRetira tallos gruesos.\nMasajea con aceite de oliva.\nSazona con sal y especias.\nExtiende en bandeja sin solapar.\nHornea a 150°C hasta que estén crujientes.",
                'is_active' => true,
            ],
            [
                'name' => 'Batido verde detox',
                'description' => 'Bebida depurativa con vegetales verdes y frutas dulces.',
                'ingredients' => "Espinacas baby\nApio\nPepino\nManzana verde\nJengibre\nLimón\nAgua de coco\nMenta",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 8,
                'calories_per_serving' => 120,
                'protein' => 3,
                'carbohydrates' => 28,
                'fats' => 1,
                'servings' => 1,
                'preparation' => "Lava todos los vegetales.\nCorta en trozos para facilitar licuado.\nAñade agua de coco como base.\nLicúa hasta obtener consistencia suave.\nCuela si prefieres textura más lisa.\nSirve inmediatamente con hielo.",
                'is_active' => true,
            ],
            [
                'name' => 'Crackers de semillas caseros',
                'description' => 'Galletas crujientes hechas completamente con semillas nutritivas.',
                'ingredients' => "Semillas de girasol\nSemillas de calabaza\nSemillas de lino\nSemillas de sésamo\nSal marina\nAceite de oliva\nAgua",
                'category' => 'Snack',
                'difficulty' => 'intermedio',
                'preparation_time' => 45,
                'calories_per_serving' => 180,
                'protein' => 8,
                'carbohydrates' => 6,
                'fats' => 15,
                'servings' => 4,
                'preparation' => "Mezcla todas las semillas secas.\nAñade sal, aceite y agua gradualmente.\nForma masa compacta y deja reposar.\nExtiende fina entre papeles encerados.\nCorta en rectángulos.\nHornea hasta dorar y esté crujiente.",
                'is_active' => true,
            ],
            [
                'name' => 'Rollitos de pepino con queso',
                'description' => 'Aperitivo fresco y ligero perfecto para días calurosos.',
                'ingredients' => "Pepino largo\nQueso crema\nSalmón ahumado\nEneldo fresco\nLimón\nPimienta negra",
                'category' => 'Snack',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 150,
                'protein' => 12,
                'carbohydrates' => 6,
                'fats' => 10,
                'servings' => 2,
                'preparation' => "Corta pepino en láminas finas con mandolina.\nMezcla queso crema con eneldo picado.\nExtiende mezcla sobre láminas de pepino.\nAñade tiras de salmón ahumado.\nEnrolla cuidadosamente.\nSujeta con palillo si es necesario.",
                'is_active' => true,
            ],

            // POSTRE (10 comidas)
            [
                'name' => 'Parfait de yogur y frutas',
                'description' => 'Postre en capas cremoso y refrescante con frutas naturales.',
                'ingredients' => "Yogur griego\nFrutos rojos\nGranola casera\nMiel pura\nVainilla\nMenta fresca",
                'category' => 'Postre',
                'difficulty' => 'fácil',
                'preparation_time' => 10,
                'calories_per_serving' => 220,
                'protein' => 12,
                'carbohydrates' => 32,
                'fats' => 6,
                'servings' => 2,
                'preparation' => "Mezcla yogur con vainilla y miel.\nEn vasos transparentes alterna capas.\nComienza con yogur en el fondo.\nAñade frutas y granola.\nRepite capas hasta llenar vaso.\nDecora con menta fresca encima.",
                'is_active' => true,
            ],
            [
                'name' => 'Pudín de chía con mango',
                'description' => 'Postre cremoso rico en omega-3 con sabor tropical.',
                'ingredients' => "Semillas de chía\nLeche de coco\nMango maduro\nMiel\nVainilla\nCoco rallado",
                'category' => 'Postre',
                'difficulty' => 'fácil',
                'preparation_time' => 10,
                'calories_per_serving' => 190,
                'protein' => 6,
                'carbohydrates' => 28,
                'fats' => 8,
                'servings' => 2,
                'preparation' => "Mezcla chía con leche de coco.\nAñade miel y vainilla.\nRefrigera 4 horas hasta gelificar.\nCorta mango en cubos pequeños.\nSirve pudín en copas.\nDecora con mango y coco rallado.",
                'is_active' => true,
            ],
            [
                'name' => 'Manzanas al horno con canela',
                'description' => 'Postre tradicional aromático sin azúcar añadida.',
                'ingredients' => "Manzanas\nCanela en polvo\nNueces picadas\nMiel\nMantequilla\nVainilla",
                'category' => 'Postre',
                'difficulty' => 'fácil',
                'preparation_time' => 35,
                'calories_per_serving' => 180,
                'protein' => 3,
                'carbohydrates' => 35,
                'fats' => 6,
                'servings' => 4,
                'preparation' => "Ahue ca manzanas retirando corazón.\nMezcla nueces, canela y miel.\nRellena manzanas con mezcla.\nAñade punto de mantequilla encima.\nHornea 25 minutos hasta tiernas.\nSirve calientes con su jugo.",
                'is_active' => true,
            ],
            [
                'name' => 'Helado de plátano casero',
                'description' => 'Helado cremoso de un solo ingrediente, naturalmente dulce.',
                'ingredients' => "Plátanos congelados\nLeche de almendras\nVainilla\nCanela\nCacao en polvo\nAlmendras",
                'category' => 'Postre',
                'difficulty' => 'fácil',
                'preparation_time' => 5,
                'calories_per_serving' => 140,
                'protein' => 3,
                'carbohydrates' => 32,
                'fats' => 2,
                'servings' => 2,
                'preparation' => "Procesa plátanos congelados hasta cremoso.\nAñade leche si necesita más suavidad.\nIncorpora vainilla y canela.\nSirve inmediatamente como helado suave.\nDecora con almendras y cacao.\nCongela para consistencia más firme.",
                'is_active' => true,
            ],
            [
                'name' => 'Brownies de porotos negros',
                'description' => 'Brownies saludables con base de legumbres y cacao intenso.',
                'ingredients' => "Porotos negros cocidos\nCacao en polvo\nHuevos\nMiel\nVainilla\nPolvo de hornear\nChispas de chocolate negro",
                'category' => 'Postre',
                'difficulty' => 'intermedio',
                'preparation_time' => 40,
                'calories_per_serving' => 160,
                'protein' => 6,
                'carbohydrates' => 28,
                'fats' => 4,
                'servings' => 8,
                'preparation' => "Procesa porotos hasta formar puré suave.\nMezcla con huevos, miel y vainilla.\nIncorpora cacao y polvo de hornear.\nAñade chispas de chocolate.\nVierte en molde engrasado.\nHornea 25 minutos hasta que al insertar palillo salga limpio.",
                'is_active' => true,
            ],
            [
                'name' => 'Gelatina de frutas naturales',
                'description' => 'Postre refrescante con gelatina sin sabor y frutas reales.',
                'ingredients' => "Gelatina sin sabor\nJugo de frutas natural\nFrutas frescas\nMiel\nAgua\nMenta",
                'category' => 'Postre',
                'difficulty' => 'fácil',
                'preparation_time' => 15,
                'calories_per_serving' => 80,
                'protein' => 4,
                'carbohydrates' => 18,
                'fats' => 0,
                'servings' => 4,
                'preparation' => "Hidrata gelatina en agua fría.\nCalienta jugo con miel hasta tibio.\nDisuelve gelatina en jugo caliente.\nDeja enfriar a temperatura ambiente.\nAñade frutas cortadas en trozos.\nRefrigera hasta cuajar completamente.",
                'is_active' => true,
            ],
            [
                'name' => 'Trufas de cacao y dátiles',
                'description' => 'Bombones saludables endulzados naturalmente con frutas.',
                'ingredients' => "Dátiles sin hueso\nCacao en polvo\nAlmendras\nAceite de coco\nVainilla\nCoco rallado",
                'category' => 'Postre',
                'difficulty' => 'fácil',
                'preparation_time' => 20,
                'calories_per_serving' => 120,
                'protein' => 3,
                'carbohydrates' => 18,
                'fats' => 6,
                'servings' => 8,
                'preparation' => "Remoja dátiles hasta ablandar.\nProcesa con almendras hasta formar pasta.\nAñade cacao, aceite y vainilla.\nForma bolitas con las manos.\nRueda en coco rallado.\nRefrigera hasta que estén firmes.",
                'is_active' => true,
            ],
            [
                'name' => 'Panna cotta de vainilla',
                'description' => 'Postre italiano sedoso y delicado con aroma a vainilla.',
                'ingredients' => "Leche\nCrema de leche\nGelatina sin sabor\nAzúcar de coco\nVainilla\nFrutos rojos",
                'category' => 'Postre',
                'difficulty' => 'intermedio',
                'preparation_time' => 25,
                'calories_per_serving' => 180,
                'protein' => 6,
                'carbohydrates' => 18,
                'fats' => 10,
                'servings' => 4,
                'preparation' => "Hidrata gelatina en leche fría.\nCalienta crema con azúcar y vainilla.\nDisuelve gelatina en mezcla caliente.\nCuela para eliminar grumos.\nVierte en moldes individuales.\nRefrigera 4 horas hasta cuajar.\nDecora con frutos rojos.",
                'is_active' => true,
            ],
            [
                'name' => 'Crumble de manzana y avena',
                'description' => 'Postre rústico con frutas horneadas y cobertura crujiente.',
                'ingredients' => "Manzanas\nAvena en hojuelas\nHarina integral\nMantequilla\nCanela\nMiel\nNueces",
                'category' => 'Postre',
                'difficulty' => 'intermedio',
                'preparation_time' => 45,
                'calories_per_serving' => 220,
                'protein' => 5,
                'carbohydrates' => 38,
                'fats' => 8,
                'servings' => 6,
                'preparation' => "Pela y corta manzanas en gajos.\nMezcla con canela y miel.\nCombina avena, harina y mantequilla fría.\nForma crumble con los dedos.\nColoca manzanas en molde.\nCubre con crumble y nueces.\nHornea hasta dorar la superficie.",
                'is_active' => true,
            ],
            [
                'name' => 'Sorbete de limón casero',
                'description' => 'Postre helado refrescante con cítricos naturales.',
                'ingredients' => "Limones frescos\nAgua\nMiel\nClaras de huevo\nMenta fresca\nRalladura de limón",
                'category' => 'Postre',
                'difficulty' => 'intermedio',
                'preparation_time' => 30,
                'calories_per_serving' => 90,
                'protein' => 2,
                'carbohydrates' => 22,
                'fats' => 0,
                'servings' => 4,
                'preparation' => "Prepara jarabe con agua y miel.\nAñade jugo y ralladura de limón.\nDeja enfriar completamente.\nBate claras a punto de nieve.\nIncorpora al jarabe frío.\nCongela removiendo cada 30 minutos.\nSirve con menta fresca.",
                'is_active' => true,
            ],
        ];

        foreach ($foods as $foodData) {
            $food = Food::create($foodData);
            
            // Crear una imagen por defecto para cada comida
            FoodImage::create([
                'food_id' => $food->id,
                'path' => 'test',
                'position' => 0,
            ]);
        }
    }
}
